site_name: PughLab-guides

nav:
- Home: 'index.md'
- Galaxy: 'galaxy.md'
- Planemo: 'planemo.md'
- CAC: 'CAC.md'
- Frontend Deployment: 'Frontend Deployment.md'
- Backend Deployment: 'Backend Deployment.md'
- PEGR: 'pegr.md'
- Lab Websites: 'labwebsite.md'
- FAQ: 'FAQ.md'


theme:
  name: 'gitbook'
  shortcuts:
        help: 191    # ?
        next: 78     # n
        previous: 80 # p
        search: 83   # s

plugins: []

repo_url: https://github.com/CEGRcode/labtutorial

markdown_extensions:
    - toc:
        permalink: "#"
