site_name: PughLab-guides

nav:
- Home: 'index.md'
- Buffers: 'Buffers.md'
- Yeast: 'Yeast.md'


theme:
  name: 'readthedocs'
  shortcuts:
        help: 191    # ?
        next: 78     # n
        previous: 80 # p
        search: 83   # s

repo_url: https://github.com/CEGRcode/GeneralLab

markdown_extensions:
    - toc:
        permalink: "#"
