site_name: PughLab-guides

nav:
- Home: 'index.md'
- Galaxy: 'galaxy.md'
- Planemo: 'planemo.md'
- Frontend Deployment: 'Frontend Deployment.md'
- Backend Deployment: 'Backend Deployment.md'
- PEGR: 'pegr.md'
- FAQ: 'FAQ.md'


theme:
  name: 'readthedocs'
  shortcuts:
        help: 191    # ?
        next: 78     # n
        previous: 80 # p
        search: 83   # s

repo_url: https://github.com/CEGRcode/labtutorial

markdown_extensions:
    - toc:
        permalink: "#"
